export const SAMPLE_QUIZZES = [
  {
    id: 1,
    url: 'https://en.wikipedia.org/wiki/Alan_Turing',
    title: 'Alan Turing',
    summary:
      'Alan Turing was a British mathematician, computer scientist, logician, cryptanalyst, and philosopher. He is widely considered the father of theoretical computer science and artificial intelligence. His work during World War II played a crucial role in breaking the German Enigma code.',
    article_image: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Alan_Turing_Aged_16.jpg',
    sections: [
      {
        title: 'Early Life & Education',
        description: 'Turing studied mathematics at King\'s College, Cambridge, where he showed exceptional academic ability.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/King%27s_College%2C_Cambridge.jpg',
      },
      {
        title: 'World War II & Cryptography',
        description: 'During WWII, Turing worked at Bletchley Park and helped break the German Enigma code.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Bombe-replica.jpg',
      },
      {
        title: 'Artificial Intelligence',
        description: 'Turing proposed the famous Turing Test to determine whether a machine can exhibit intelligent behavior.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Turing_Test.png',
      },
      {
        title: 'Legacy & Impact',
        description: 'The Turing Award is named in his honor and is considered the Nobel Prize of computing.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/8/83/Turing_Award.jpg',
      },
    ],
    quiz: [
      {
        question: 'Where did Alan Turing complete his undergraduate studies?',
        options: ['Harvard University', 'Cambridge University', 'Oxford University', 'Stanford University'],
        answer: 'Cambridge University',
        difficulty: 'easy' as const,
        topic: 'Early Life & Education',
        explanation: 'Alan Turing studied mathematics at King\'s College, Cambridge, as mentioned in the Early Life section.',
      },
      {
        question: 'What was the primary purpose of the Bombe machine developed by Alan Turing?',
        options: [
          'Encrypt British military messages',
          'Decode Morse code transmissions',
          'Break the German Enigma cipher',
          'Predict enemy troop movements',
        ],
        answer: 'Break the German Enigma cipher',
        difficulty: 'medium' as const,
        topic: 'World War II & Cryptography',
        explanation: 'The Bombe was designed to decrypt messages encrypted by the German Enigma machine during WWII.',
      },
      {
        question: 'What does the Turing Test evaluate?',
        options: [
          'Machine speed',
          'Machine learning accuracy',
          'Human-like intelligence in machines',
          'Hardware efficiency',
        ],
        answer: 'Human-like intelligence in machines',
        difficulty: 'medium' as const,
        topic: 'Artificial Intelligence',
        explanation: 'The Turing Test measures whether a machine can imitate human intelligence convincingly.',
      },
      {
        question: 'Which concept introduced by Turing laid the foundation for modern computing?',
        options: ['Neural Networks', 'Turing Machine', 'Binary Search', 'Compiler Design'],
        answer: 'Turing Machine',
        difficulty: 'hard' as const,
        topic: 'Artificial Intelligence',
        explanation: 'The Turing Machine is a theoretical model that defines computation and underpins computer science.',
      },
      {
        question: 'Which prestigious award is named after Alan Turing?',
        options: ['Nobel Prize', 'Fields Medal', 'Turing Award', 'Abel Prize'],
        answer: 'Turing Award',
        difficulty: 'easy' as const,
        topic: 'Legacy & Impact',
        explanation: 'The Turing Award honors major contributions to computer science.',
      },
    ],
    related_topics: [
      { name: 'Cryptography', image: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Cryptography.jpg' },
      { name: 'Enigma Machine', image: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Enigma-machine.jpg' },
      { name: 'History of Computer Science', image: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Computer_history_museum.jpg' },
      { name: 'Artificial Intelligence', image: 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Artificial_Intelligence_logo.svg' },
    ],
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 2,
    url: 'https://en.wikipedia.org/wiki/Ada_Lovelace',
    title: 'Ada Lovelace',
    summary:
      'Augusta Ada King, Countess of Lovelace was an English mathematician widely known as the first computer programmer. She wrote the first algorithm intended for machine processing and is regarded as a visionary in computing.',
    article_image: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Ada_Lovelace_portrait.jpg',
    sections: [
      {
        title: 'Early Life & Education',
        description: 'Ada received extensive tutoring in mathematics and science, which was unusual for women at the time.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Ada_Lovelace_portrait.jpg',
      },
      {
        title: 'The Analytical Engine',
        description: 'She documented Babbage\'s Analytical Engine and added notes that were three times longer than the original article.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Charles_Babbage_portrait.jpg',
      },
      {
        title: 'Computing Innovation',
        description: 'Ada recognized that the machine could manipulate symbols according to rules, a visionary concept for the 1840s.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Analytical_Engine.jpg',
      },
      {
        title: 'Legacy',
        description: 'She is celebrated as the first computer programmer and a pioneer in recognizing the potential of computing machines.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/London_Scene.jpg',
      },
    ],
    quiz: [
      {
        question: 'What is Ada Lovelace widely known for?',
        options: ['Inventing the World Wide Web', 'First computer programmer', 'Developing JavaScript', 'Creating Python'],
        answer: 'First computer programmer',
        difficulty: 'easy' as const,
        topic: 'Early Life & Education',
        explanation: 'Lovelace wrote the first algorithm intended for a machine.',
      },
      {
        question: 'Who designed the machine Ada wrote algorithms for?',
        options: ['Charles Babbage', 'Alan Turing', 'John von Neumann', 'Claude Shannon'],
        answer: 'Charles Babbage',
        difficulty: 'easy' as const,
        topic: 'The Analytical Engine',
        explanation: 'She wrote the algorithm for Babbage\'s Analytical Engine.',
      },
      {
        question: 'What language did Ada refer to when writing algorithms?',
        options: ['Binary', 'English', 'Mathematical notation', 'C++'],
        answer: 'Mathematical notation',
        difficulty: 'medium' as const,
        topic: 'Computing Innovation',
        explanation: 'She used advanced math expressions for the analytical engine.',
      },
      {
        question: 'What year was Ada Lovelace born?',
        options: ['1815', '1901', '1850', '1784'],
        answer: '1815',
        difficulty: 'medium' as const,
        topic: 'Early Life & Education',
        explanation: 'She was born in 1815 in London.',
      },
      {
        question: 'With which mathematical institution was Ada connected?',
        options: ['Royal Society', 'University of Cambridge', 'Royal Astronomical Society', 'London Mathematical Society'],
        answer: 'Royal Astronomical Society',
        difficulty: 'hard' as const,
        topic: 'Legacy',
        explanation: 'She corresponded with members of major scientific bodies.',
      },
    ],
    related_topics: [
      { name: 'Charles Babbage', image: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Charles_Babbage_portrait.jpg' },
      { name: 'Analytical Engine', image: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Analytical_Engine.jpg' },
      { name: 'History of Computing', image: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Computer_history_museum.jpg' },
      { name: 'Women in Science', image: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/London_Scene.jpg' },
    ],
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 3,
    url: 'https://en.wikipedia.org/wiki/Nikola_Tesla',
    title: 'Nikola Tesla',
    summary:
      'Nikola Tesla was a Serbian-American inventor and electrical engineer who pioneered alternating current systems. He is widely regarded as one of the most prolific inventors and engineers of all time.',
    article_image: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/N.Tesla.JPG',
    sections: [
      {
        title: 'Early Innovation',
        description: 'Tesla began his career with groundbreaking work in electrical systems and invented the rotating magnetic field.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/AC_Power_Transmission.jpg',
      },
      {
        title: 'AC Power Revolution',
        description: 'Tesla partnered with Westinghouse to develop and promote alternating current technology worldwide.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/George_Westinghouse.jpg',
      },
      {
        title: 'Innovations & Inventions',
        description: 'Tesla created numerous inventions including AC motors, dynamos, transformers, and wireless transmission systems.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/4/49/AC_Dynamo.jpg',
      },
      {
        title: 'Global Impact',
        description: 'Tesla\'s AC system became the basis for the global electrical grid that powers modern civilization.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Smiljan.jpg',
      },
    ],
    quiz: [
      {
        question: 'What field is Nikola Tesla most known for?',
        options: ['Aeronautics', 'Electricity', 'Medicine', 'Architecture'],
        answer: 'Electricity',
        difficulty: 'easy' as const,
        topic: 'Early Innovation',
        explanation: 'Tesla pioneered alternating current (AC) systems.',
      },
      {
        question: 'What company did Tesla work with early in his career?',
        options: ['General Electric', 'Westinghouse', 'Tesla Motors', 'Siemens'],
        answer: 'Westinghouse',
        difficulty: 'easy' as const,
        topic: 'AC Power Revolution',
        explanation: 'He partnered with Westinghouse to promote AC power.',
      },
      {
        question: 'Which invention is Tesla credited with?',
        options: ['Light bulb', 'Radio', 'Dynamo', 'Flying machine'],
        answer: 'Dynamo',
        difficulty: 'medium' as const,
        topic: 'Innovations & Inventions',
        explanation: 'His work included AC dynamos and motors.',
      },
      {
        question: 'Where was Tesla born?',
        options: ['USA', 'Croatia', 'France', 'India'],
        answer: 'Croatia',
        difficulty: 'medium' as const,
        topic: 'Early Innovation',
        explanation: 'Tesla was born in Smiljan, modern-day Croatia.',
      },
      {
        question: 'What form of current did Tesla advocate?',
        options: ['DC', 'AC', 'Hybrid', 'Solar'],
        answer: 'AC',
        difficulty: 'hard' as const,
        topic: 'Global Impact',
        explanation: 'Tesla championed Alternating Current systems.',
      },
    ],
    related_topics: [
      { name: 'AC Power', image: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/AC_Power_Transmission.jpg' },
      { name: 'Westinghouse', image: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/George_Westinghouse.jpg' },
      { name: 'Electrical Engineering', image: 'https://upload.wikimedia.org/wikipedia/commons/4/49/AC_Dynamo.jpg' },
      { name: 'Energy Systems', image: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Smiljan.jpg' },
    ],
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 4,
    url: 'https://en.wikipedia.org/wiki/Marie_Curie',
    title: 'Marie Curie',
    summary:
      'Marie Curie was a Polish and naturalized-French physicist and chemist who conducted pioneering research on radioactivity. She was the first woman to win a Nobel Prize and remains the only person to win Nobel Prizes in two scientific fields.',
    article_image: 'https://upload.wikimedia.org/wikipedia/commons/6/69/Marie_Curie_c1920.jpg',
    sections: [
      {
        title: 'Early Career',
        description: 'Marie began her scientific career in France, studying the mysterious rays emitted by uranium.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Radioactivity_Diagram.jpg',
      },
      {
        title: 'Radioactivity Discovery',
        description: 'She discovered and isolated two new elements: polonium and radium, changing our understanding of matter.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Radium_Sample.jpg',
      },
      {
        title: 'Nobel Recognition',
        description: 'Marie won the Nobel Prize in Physics for discovering radioactivity and in Chemistry for discovering radium.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Nobel_Prize.jpg',
      },
      {
        title: 'Legacy',
        description: 'She established the Curie Institutes and advanced medical research, particularly in cancer treatment.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/0/03/Warsaw.jpg',
      },
    ],
    quiz: [
      {
        question: 'What did Marie Curie discover?',
        options: ['DNA', 'Radioactivity', 'Vaccines', 'Electricity'],
        answer: 'Radioactivity',
        difficulty: 'easy' as const,
        topic: 'Early Career',
        explanation: 'She pioneered research in radioactivity.',
      },
      {
        question: 'Which two elements did she isolate?',
        options: ['Oxygen & Hydrogen', 'Radium & Polonium', 'Gold & Silver', 'Uranium & Plutonium'],
        answer: 'Radium & Polonium',
        difficulty: 'easy' as const,
        topic: 'Radioactivity Discovery',
        explanation: 'She discovered and named radium and polonium.',
      },
      {
        question: 'Marie Curie won how many Nobel Prizes?',
        options: ['One', 'Two', 'Three', 'None'],
        answer: 'Two',
        difficulty: 'medium' as const,
        topic: 'Nobel Recognition',
        explanation: 'She won in Physics and Chemistry.',
      },
      {
        question: 'Where was Curie born?',
        options: ['Poland', 'France', 'Germany', 'Russia'],
        answer: 'Poland',
        difficulty: 'medium' as const,
        topic: 'Early Career',
        explanation: 'She was born in Warsaw, Poland.',
      },
      {
        question: 'What lab did Curie work in?',
        options: ['University of Oxford', 'Sorbonne', 'MIT', 'Caltech'],
        answer: 'Sorbonne',
        difficulty: 'hard' as const,
        topic: 'Legacy',
        explanation: 'She conducted research at the Sorbonne in Paris.',
      },
    ],
    related_topics: [
      { name: 'Radioactivity', image: 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Radioactivity_Diagram.jpg' },
      { name: 'Chemistry', image: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Radium_Sample.jpg' },
      { name: 'Nobel Prize', image: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Nobel_Prize.jpg' },
      { name: 'Physics', image: 'https://upload.wikimedia.org/wikipedia/commons/0/03/Warsaw.jpg' },
    ],
    created_at: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: 5,
    url: 'https://en.wikipedia.org/wiki/Albert_Einstein',
    title: 'Albert Einstein',
    summary:
      'Albert Einstein was a German-born theoretical physicist who developed the theory of relativity, one of the two pillars of modern physics. His mass–energy equivalence formula E=mc² is one of the most famous equations in physics.',
    article_image: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Albert_Einstein_Head.jpg',
    sections: [
      {
        title: 'Early Work',
        description: 'Einstein began his career by questioning classical physics and proposing revolutionary new theories.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/2/23/E%3Dmc2_formula.jpg',
      },
      {
        title: 'Theory of Relativity',
        description: 'He developed both special relativity and general relativity, transforming our understanding of space and time.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Ulm_Cathedral.jpg',
      },
      {
        title: 'Nobel Prize & Recognition',
        description: 'Einstein received the Nobel Prize in Physics for his explanation of the photoelectric effect.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Nobel_Prize_Physics.jpg',
      },
      {
        title: 'Lasting Legacy',
        description: 'His theories are fundamental to modern physics and have applications in GPS, nuclear energy, and cosmology.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Relativity_Concept.jpg',
      },
    ],
    quiz: [
      {
        question: 'Einstein is best known for which formula?',
        options: ['F = ma', 'E = mc²', 'P = IV', 'a² + b² = c²'],
        answer: 'E = mc²',
        difficulty: 'easy' as const,
        topic: 'Early Work',
        explanation: 'His mass–energy equivalence formula.',
      },
      {
        question: 'Where was he born?',
        options: ['USA', 'Germany', 'Russia', 'France'],
        answer: 'Germany',
        difficulty: 'easy' as const,
        topic: 'Early Work',
        explanation: 'He was born in Ulm, Germany.',
      },
      {
        question: 'In which field did Einstein win Nobel Prize?',
        options: ['Chemistry', 'Literature', 'Physics', 'Peace'],
        answer: 'Physics',
        difficulty: 'medium' as const,
        topic: 'Nobel Prize & Recognition',
        explanation: 'He won for the photoelectric effect.',
      },
      {
        question: 'Einstein worked on which theory?',
        options: ['Thermodynamics', 'Relativity', 'Quantum computing', 'Evolution'],
        answer: 'Relativity',
        difficulty: 'medium' as const,
        topic: 'Theory of Relativity',
        explanation: 'He developed special and general relativity.',
      },
      {
        question: 'What instrument did Einstein contribute to?',
        options: ['Telescope', 'Light bulb', 'GPS theory', 'Human genome'],
        answer: 'GPS theory',
        difficulty: 'hard' as const,
        topic: 'Lasting Legacy',
        explanation: 'Relativity is essential for GPS accuracy.',
      },
    ],
    related_topics: [
      { name: 'Physics', image: 'https://upload.wikimedia.org/wikipedia/commons/2/23/E%3Dmc2_formula.jpg' },
      { name: 'Relativity', image: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Ulm_Cathedral.jpg' },
      { name: 'Nobel Prize', image: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Nobel_Prize_Physics.jpg' },
      { name: 'Modern Physics', image: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Relativity_Concept.jpg' },
    ],
    created_at: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: 6,
    url: 'https://en.wikipedia.org/wiki/Grace_Hopper',
    title: 'Grace Hopper',
    summary:
      'Grace Hopper was an American computer scientist and US Navy rear admiral who pioneered computer programming. She was one of the first programmers of the ENIAC and is known for her work on the first compiler.',
    article_image: 'https://upload.wikimedia.org/wikipedia/commons/3/37/Grace_Hopper.png',
    sections: [
      {
        title: 'Early Career in Computing',
        description: 'Grace was one of the first programmers, working on ENIAC and breaking new ground in computer science.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/4/47/Compiler_Diagram.jpg',
      },
      {
        title: 'Compiler Development',
        description: 'She pioneered the concept of compilers and helped develop COBOL, making programming more accessible.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/COBOL_Code.jpg',
      },
      {
        title: 'Military Service',
        description: 'Hopper served as a Rear Admiral in the U.S. Navy and championed the use of high-level programming languages.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/1/15/US_Navy_Logo.png',
      },
      {
        title: 'Legacy & Impact',
        description: 'She revolutionized programming by advocating for code that humans could read, not just machines.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/8/89/US_Navy_ship.jpg',
      },
    ],
    quiz: [
      {
        question: 'What did Grace Hopper pioneer?',
        options: ['Web design', 'Compilers', 'Artificial Intelligence', 'Blockchain'],
        answer: 'Compilers',
        difficulty: 'easy' as const,
        topic: 'Early Career in Computing',
        explanation: 'She helped develop the first compiler.',
      },
      {
        question: 'Which programming language was Hopper instrumental in?',
        options: ['BASIC', 'COBOL', 'Python', 'Fortran'],
        answer: 'COBOL',
        difficulty: 'easy' as const,
        topic: 'Compiler Development',
        explanation: 'She led COBOL development.',
      },
      {
        question: 'What was Hopper\'s nickname?',
        options: ['Mother of AI', 'Queen of Code', 'Amazing Grace', 'Compiler Queen'],
        answer: 'Amazing Grace',
        difficulty: 'medium' as const,
        topic: 'Legacy & Impact',
        explanation: 'She was nicknamed "Amazing Grace" by colleagues.',
      },
      {
        question: 'Hopper served in which branch?',
        options: ['Army', 'Navy', 'Air Force', 'Marines'],
        answer: 'Navy',
        difficulty: 'medium' as const,
        topic: 'Military Service',
        explanation: 'She was a US Navy Rear Admiral.',
      },
      {
        question: 'What major concept is Hopper associated with?',
        options: ['Blockchain', 'Machine Learning', 'High-level languages', 'Networking'],
        answer: 'High-level languages',
        difficulty: 'hard' as const,
        topic: 'Legacy & Impact',
        explanation: 'She advocated for user-friendly code.',
      },
    ],
    related_topics: [
      { name: 'COBOL', image: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/COBOL_Code.jpg' },
      { name: 'Programming Languages', image: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Computer_Languages.jpg' },
      { name: 'Computer Science History', image: 'https://upload.wikimedia.org/wikipedia/commons/4/47/Compiler_Diagram.jpg' },
      { name: 'Women in Computing', image: 'https://upload.wikimedia.org/wikipedia/commons/1/15/US_Navy_Logo.png' },
    ],
    created_at: new Date(Date.now() - 518400000).toISOString(),
  },
]
